### ISSUE TITLE
Java 9

### ISSUE THREAD

**Issue by Waverunner** [Waverunner/HarvesterDroid#16]
Update for Java 9

- [ ] #17 Break apart app into more manageable code
- [ ] #15 Resource Refactor for multiple trackers
- [ ] #13 Test Cases implemented

**Comment by Waverunner** [comment]
Will be moving over to Kotlin instead
